#!/usr/bin/env bash

set -x

dir=$1

if [ -z $dir ]; then
  echo "bare_to_repo: directory not provided"
  exit 1
fi

cwd=$(pwd)

set +x

for repo in "$cwd/$dir"*/; do
  [ -d "$repo" ] || continue
  git clone "${repo}" "${cwd}/repos/$(basename "$repo")" || true
done
