#!/usr/bin/env bash

set -x

dir=$1

if [ -z $dir ]; then
  echo "run: directory not provided"
  exit 1
fi

shift

cwd=$(pwd)

set +x

repo="$cwd/$dir"
[ ! -d "$repo" ] && exit 1

git -C "$repo" bundle create "$(basename "$repo")".bundle --all
