#!/usr/bin/env bash

set -x

dir=$1

if [ -z $dir ]; then
  echo "run: directory not provided"
  exit 1
fi

shift

cwd=$(pwd)

set +x

for repo in "$cwd/$dir"*/; do
  [ -d "$repo" ] || continue

  git -C "$repo" bundle create "$(basename "$repo")".bundle --all
done
