#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
. "$SCRIPT_DIR/vars"

cat git.repos | while IFS= read -r repo; do
  git clone "ssh://${REMOTE_NAME}${TARGET_GIT_REPOS}/$repo" "$GIT_REPO/repos/$repo" || true
done
