#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
. "$SCRIPT_DIR/vars"

set -x

usage() {
  echo "mirror_to [OPTIONS]"
  echo
  echo "Options:"
  echo "  -h        Display this message and exits"
  echo "  -f        Use --delete in rsync"
  echo "  -p [PORT] Port to access over ssh"
}

while getopts ":-fp:" opt; do
  case "$opt" in
  -)
    break
    ;;
  h)
    usage
    exit 0
    ;;
  f)
    FORCE=1
    ;;
  p)
    PORT=$OPTARG
    ;;
  ?)
    echo "Error: Invalid option '-$OPTARG'" >&2
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

if [ -n "$FORCE" ]; then
  OPERATION=delete
else
  OPERATION=update
fi

if [ -n "$PORT" ]; then
  rsync -e "ssh -p ${PORT}" -avzrPl --"$OPERATION" "$GIT_REPO" "$REMOTE_NAME:$TARGET_GIT"
else
  rsync -avzrPl --"$OPERATION" "$GIT_REPO" "$REMOTE_NAME:$TARGET_GIT"
fi
