#!/usr/bin/env bash

set -x

dir=$1

if [ -z $dir ]; then
  echo "run: directory not provided"
  exit 1
fi

shift

cwd=$(pwd)

set +x

for repo in "$cwd/$dir"*/; do
  [ -d "$repo" ] || continue

  result="$(git -C "$repo" status)"
  if [[ $result =~ "working tree clean" ]]; then
    printf ""
  else
    info "git -C $repo status"
    echo "$result"
  fi
done
