#!/usr/bin/env bash

dir=$1

if [ -z $dir ]; then
  echo "repo_to_bare: directory not provided"
  exit 1
fi

cwd=$(pwd)

for repo in "$cwd/$dir"*/; do
  [ -d "$repo" ] || continue
  git clone  "$repo" "${GIT_SERVER}/$(basename "$repo")" --bare || info "Already cloned"
done
