#!/usr/bin/env bash

set -x

dir=$1

if [ -z $dir ]; then
  echo "repo_to_bare: directory not provided"
  exit 1
fi

cwd=$(pwd)

set +x

for repo in "$cwd/$dir"*/; do
  [ -d "$repo" ] || continue
  git clone  "$repo" "${GIT_SERVER}/server/$(basename "$repo")" --bare || true
done
