#!/usr/bin/env bash

dir=$1

if [ -z $dir ]; then
  echo "run: directory not provided"
  exit 1
fi

shift

cwd=$(pwd)

[ -z "$1" ] && {
  echo "run: command not provided"
  exit 1
}

files=()
for repo in "$cwd/$dir"*/; do
  [ -d "$repo" ] || continue

  info "git -C $repo $@"
  git -C "$repo" "$@"
done
