#!/usr/bin/env bash

get() {
  sed -n "s|^$1=||p" $2
}

current=$(get current repo.ini)
server_home=$(get server repo.ini)
client_home=$(get client repo.ini)
server_name=$(get server_name repo.ini)
client_name=$(get client_name repo.ini)
git_repo=$(get git_repo repo.ini)

[ -z $current ] && {
  echo "vars: current not set"
  exit 1
}
[ -z $server_home ] && {
  echo "vars: server_home not set"
  exit 1
}
[ -z $client_home ] && {
  echo "vars: client_home not set"
  exit 1
}
[ -z $server_name ] && {
  echo "vars: server_name not set"
  exit 1
}
[ -z $client_name ] && {
  echo "vars: client_name not set"
  exit 1
}
[ -z $git_repo ] && {
  echo "vars: git_repo not set"
  exit 1
}

if [ "$current" = "client" ]; then
  GIT_REPO="${client_home}/${git_repo}"
  TARGET="server"
  TARGET_GIT="${server_home}/${git_repo}/"
  TARGET_GIT_REPOS="${server_home}/${git_repo}/repos"
  TARGET_GIT_SERVER="${server_home}/${git_repo}/server"
  REMOTE_NAME="${server_name}"
elif [ "$current" = "server" ]; then
  GIT_REPO="${server_home}/${git_repo}"
  TARGET="client"
  TARGET_GIT="${client_home}/${git_repo}/"
  TARGET_GIT_REPOS="${client_home}/${git_repo}/repos"
  TARGET_GIT_SERVER="${client_home}/${git_repo}/server"
  REMOTE_NAME="${client_name}"
fi

GIT_SERVER="${GIT_REPO}/server"
GIT_REPOS="${GIT_REPO}/repos"

mkdir -p "${GIT_SERVER}"
mkdir -p "${GIT_REPOS}"

BLUE="$(tput setaf 87)"
RESET=$(tput sgr0)

info() {
  echo -e "${BLUE}$@${RESET}"
}
